# Exercise 1: IT Company Employee Data
A start-up IT consulting company has four different departments: HR, Finance, IT, and Sales. Help the company organize and manage the data of its employees by performing the following tasks.

## Task 1

The company has hired 30 candidates recently. Assign the employee IDs to these 30 candidates as per the details below. Save the employee IDs in separate 1D arrays, one for each department, and print them.


In [68]:
import numpy as np

hr = np.arange(1,4)
it= np.arange(4, 19)
finance= np.arange(19, 24)
sales = np.arange(24, 31)

print("HR Department Employee IDs:",hr)
print("IT Department Employee IDs:",it)
print("Finance Department Employee IDs:",finance)
print("Sales Department Employee IDss:",sales)


HR Department Employee IDs: [1 2 3]
IT Department Employee IDs: [ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
Finance Department Employee IDs: [19 20 21 22 23]
Sales Department Employee IDss: [24 25 26 27 28 29 30]


## Task 2

Create four different 1D arrays to hold only the salaries of the employees as per the details below and print them.


In [69]:

hr_salary= [50000,60000,57000]
it_salary= [67000]
it_salary=it_salary*15 
finance_salary= [50000,60000,65000,90000,56000,65000,71000]
sales_salary = [6000,65000,50000,70000,87000]
hr=np.array(hr_salary)
it= np.array(it_salary)
sales=np.array(sales_salary)
fin=np.array(finance_salary)
print("IT Department Employee Salary:",it_salary)


IT Department Employee Salary: [67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000]


## Task 3

Calculate the department-wise average salary expenses for the 30 employees. Also, determine the department with the highest average salary expense for the employees.



In [70]:
Total_cost_HR= np.mean(hr_salary)
print("The cost to HR department:",Total_cost_HR)

Total_cost_fin= np.mean(finance_salary)
print("The cost to Finance department:",Total_cost_fin)

Total_cost_sale= np.mean(sales_salary)
print("The cost to sales department:",Total_cost_sale)

Total_cost_IT= np.mean(it_salary)
print("The cost to IT department:",Total_cost_IT)



The cost to HR department: 55666.666666666664
The cost to Finance department: 65285.71428571428
The cost to sales department: 55600.0
The cost to IT department: 67000.0


In [65]:
avg= np.array([Total_cost_HR,Total_cost_fin,Total_cost_sale,Total_cost_IT])
print(avg.max())

67000.0


## Task 4

List the highest salaries in the HR and Finance departments.


In [71]:
high_sal_hr= hr.max()
high_sal_hr




60000

In [72]:
high_sal_fin=fin.max()
high_sal_fin

90000

## Task 5

The company has decided to give a joining/signing bonus worth 5% of the gross salary to those employees who belong to the IT department. Update the salary of such employees after adding the bonus. Display the updated salaries.


In [73]:
#1D arrays hold the salaries in the IT department for all 15 employees 
it_salary= [67000.00]
it_salary=it_salary*15 
it= np.array(it_salary)
it

array([67000., 67000., 67000., 67000., 67000., 67000., 67000., 67000.,
       67000., 67000., 67000., 67000., 67000., 67000., 67000.])

In [74]:
it_bonus = it+(it* 0.05)
it_bonus

array([70350., 70350., 70350., 70350., 70350., 70350., 70350., 70350.,
       70350., 70350., 70350., 70350., 70350., 70350., 70350.])

# Exercise 2: University Admission Decision
A certain university wants to manage the admission process for its Master's programs. The university has collated some data that contains several parameters that are considered for the admission to Master's programs. The data dictionary for the data file is provided below.

Help the university authorities to analyze the data by performing the upcoming tasks.

Download the data file DS1_C4_S1_AdmissionPredict_Data_Practice.csv

## Task 1

Import the data file into a 2D array. Display the total number of rows and columns in the array.

Note: Use the below code to import the file into a 2D array. The data file and the Jupye rn totebook must be in the same workin directory.

In [5]:
from numpy import genfromtxt
import numpy as np
   

In [6]:
adm_data= genfromtxt('DS1_C4_S1_AdmissionPredict_Data_Practice.csv', delimiter=',', skip_header=1)
adm_data

array([[  1.  , 337.  , 118.  , ...,   9.65,   1.  ,   0.92],
       [  2.  , 324.  , 107.  , ...,   8.87,   1.  ,   0.76],
       [  3.  , 316.  , 104.  , ...,   8.  ,   1.  ,   0.72],
       ...,
       [398.  , 330.  , 116.  , ...,   9.45,   1.  ,   0.91],
       [399.  , 312.  , 103.  , ...,   8.78,   0.  ,   0.67],
       [400.  , 333.  , 117.  , ...,   9.66,   1.  ,   0.95]])

In [7]:
np.genfromtxt('DS1_C4_S1_AdmissionPredict_Data_Practice.csv', delimiter=',', skip_header=1) #alternative

array([[  1.  , 337.  , 118.  , ...,   9.65,   1.  ,   0.92],
       [  2.  , 324.  , 107.  , ...,   8.87,   1.  ,   0.76],
       [  3.  , 316.  , 104.  , ...,   8.  ,   1.  ,   0.72],
       ...,
       [398.  , 330.  , 116.  , ...,   9.45,   1.  ,   0.91],
       [399.  , 312.  , 103.  , ...,   8.78,   0.  ,   0.67],
       [400.  , 333.  , 117.  , ...,   9.66,   1.  ,   0.95]])

In [8]:
adm_data.shape #shape of the array ( # or rows, # of columns)

(400, 9)

### Task 2

Display the GRE score of all the students. 
Note: Slice only one column from theD array.

In [9]:
#printing GRE score of all students 
GRE_score=adm_data[:,1] # all the rows with the second collumn 
GRE_score

array([337., 324., 316., 322., 314., 330., 321., 308., 302., 323., 325.,
       327., 328., 307., 311., 314., 317., 319., 318., 303., 312., 325.,
       328., 334., 336., 340., 322., 298., 295., 310., 300., 327., 338.,
       340., 331., 320., 299., 300., 304., 307., 308., 316., 313., 332.,
       326., 322., 329., 339., 321., 327., 313., 312., 334., 324., 322.,
       320., 316., 298., 300., 311., 309., 307., 304., 315., 325., 325.,
       327., 316., 318., 328., 332., 336., 321., 314., 314., 329., 327.,
       301., 296., 294., 312., 340., 320., 322., 340., 319., 315., 317.,
       314., 316., 318., 299., 298., 301., 303., 304., 306., 331., 332.,
       323., 322., 312., 314., 317., 326., 316., 329., 338., 331., 304.,
       305., 321., 301., 320., 311., 310., 299., 290., 296., 327., 335.,
       334., 310., 308., 301., 300., 323., 319., 326., 333., 339., 303.,
       309., 323., 333., 314., 312., 316., 326., 318., 329., 332., 331.,
       340., 325., 320., 315., 326., 339., 311., 33

### Task 3

Find the total number of students who have a GRE score greater than 320.




In [75]:
#print GRE score mor than 320
indx=np.where(GRE_score>320)
GREscore_more_than_320= GRE_score[indx]
print(GREscore_more_than_320)

[337. 324. 322. 330. 321. 323. 325. 327. 328. 325. 328. 334. 336. 340.
 322. 327. 338. 340. 331. 332. 326. 322. 329. 339. 321. 327. 334. 324.
 322. 325. 325. 327. 328. 332. 336. 321. 329. 327. 340. 322. 340. 331.
 332. 323. 322. 326. 329. 338. 331. 321. 327. 335. 334. 323. 326. 333.
 339. 323. 333. 326. 329. 332. 331. 340. 325. 326. 339. 334. 332. 321.
 324. 326. 329. 322. 334. 322. 323. 321. 329. 327. 335. 331. 324. 324.
 323. 322. 336. 340. 334. 325. 328. 338. 333. 331. 330. 322. 321. 324.
 324. 324. 330. 326. 325. 329. 324. 325. 328. 324. 321. 335. 321. 324.
 326. 331. 327. 324. 325. 327. 322. 329. 321. 340. 331. 336. 324. 330.
 322. 323. 321. 323. 325. 328. 324. 327. 323. 326. 324. 327. 325. 332.
 323. 324. 326. 325. 327. 321. 322. 334. 338. 330. 324. 336. 321. 322.
 324. 340. 335. 326. 329. 324. 325. 330. 333.]


In [76]:
print('total number of student whose GRE score is more than 320:',GREscore_more_than_320.size)

total number of student whose GRE score is more than 320: 163


In [77]:
GREscore_more_than_320.shape # tell us number of rows in 1d format 

(163,)

### Task 4

What is the chance of admission of the students who have a TOEFLT O E F L score greater than 110? Display the admission chance as a percentage number by multiplying each value in the output by 100.
Hint: Identify the index location of the students who satisfy the above conditio
n.

In [78]:
TOEFL_score=adm_data[:,2] # all the rows with the second collumn 
TOEFL_score

array([118., 107., 104., 110., 103., 115., 109., 101., 102., 108., 106.,
       111., 112., 109., 104., 105., 107., 106., 110., 102., 107., 114.,
       116., 119., 119., 120., 109.,  98.,  93.,  99.,  97., 103., 118.,
       114., 112., 110., 106., 105., 105., 108., 110., 105., 107., 117.,
       113., 110., 114., 119., 110., 111.,  98., 100., 116., 112., 110.,
       103., 102.,  99.,  99., 104., 100., 101., 105., 107., 111., 112.,
       114., 107., 109., 115., 118., 112., 111., 108., 106., 114., 112.,
        99.,  95.,  93., 105., 120., 110., 115., 115., 103., 106., 107.,
       108., 109., 106.,  97.,  98.,  97.,  99., 100., 100., 120., 119.,
       113., 107., 105., 106., 104., 112., 110., 111., 117., 116., 103.,
       108., 109., 107., 110., 105., 106., 102., 104.,  99., 104., 117.,
       119., 106., 108., 106., 100., 113., 112., 112., 118., 114., 105.,
       105., 112., 113., 109., 103., 100., 116., 109., 110., 118., 115.,
       120., 112., 113., 105., 114., 116., 106., 11

In [79]:
TOEFL_score = adm_data[:, 2]
index = np.where(TOEFL_score > 110)
TOEFLscore_more_than_110 = TOEFL_score[index]
print("Index of students with TOEFL score more than 110:", index)


Index of students with TOEFL score more than 110: (array([  0,   5,  11,  12,  21,  22,  23,  24,  25,  32,  33,  34,  43,
        44,  46,  47,  49,  52,  53,  64,  65,  66,  69,  70,  71,  72,
        75,  76,  81,  83,  84,  97,  98,  99, 104, 106, 107, 108, 120,
       121, 126, 127, 128, 129, 130, 133, 134, 138, 141, 142, 143, 144,
       145, 147, 148, 150, 151, 152, 164, 171, 173, 174, 175, 176, 185,
       187, 188, 189, 190, 192, 193, 202, 203, 212, 213, 214, 215, 216,
       222, 228, 229, 234, 235, 236, 237, 242, 243, 249, 253, 254, 259,
       263, 268, 276, 283, 284, 285, 286, 287, 297, 298, 299, 307, 318,
       319, 325, 328, 330, 335, 337, 361, 362, 365, 372, 384, 385, 392,
       394, 397, 399], dtype=int64),)


In [80]:
chances_of_adm=adm_data[index,8] #printing the chance of admit for all those students 
chances_of_adm

array([[0.92, 0.9 , 0.84, 0.78, 0.7 , 0.94, 0.95, 0.97, 0.94, 0.91, 0.9 ,
        0.94, 0.87, 0.91, 0.86, 0.89, 0.78, 0.78, 0.72, 0.52, 0.55, 0.61,
        0.78, 0.94, 0.96, 0.93, 0.72, 0.74, 0.96, 0.92, 0.94, 0.86, 0.9 ,
        0.79, 0.74, 0.87, 0.91, 0.93, 0.94, 0.94, 0.85, 0.78, 0.84, 0.92,
        0.96, 0.79, 0.89, 0.8 , 0.9 , 0.92, 0.97, 0.8 , 0.81, 0.83, 0.96,
        0.93, 0.94, 0.86, 0.81, 0.89, 0.89, 0.87, 0.85, 0.9 , 0.89, 0.93,
        0.93, 0.88, 0.9 , 0.86, 0.94, 0.97, 0.97, 0.95, 0.96, 0.94, 0.93,
        0.91, 0.76, 0.71, 0.82, 0.91, 0.88, 0.85, 0.86, 0.7 , 0.76, 0.77,
        0.93, 0.85, 0.9 , 0.7 , 0.83, 0.89, 0.8 , 0.94, 0.93, 0.92, 0.89,
        0.86, 0.9 , 0.71, 0.8 , 0.79, 0.8 , 0.81, 0.8 , 0.8 , 0.83, 0.94,
        0.93, 0.91, 0.86, 0.95, 0.96, 0.96, 0.84, 0.89, 0.91, 0.95]])

### Task 5

The university decides to offer a scholarship worth $1,000 to all those students who have a GRE score greater than 315, have a TOEFL score greater than 115, and have some research experience. Determine the total number of students eligible for this scholarship. Also, display the serial number of these students.
Hint: Identify the index position of the rows satisfying the above condition and then use this data to find the serial numbers of the students.


In [81]:
res_exp=adm_data[:,-2]
res_exp

array([1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0.,
       1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0.,
       0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1.,
       0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0.

In [82]:
#print the index position as per the given condition 
indx=np.where((GRE_score>315)&(TOEFL_score>115)&(res_exp==1.0))
print(indx)

(array([  0,  22,  23,  24,  25,  32,  52,  70,  81,  97,  98, 107, 108,
       120, 121, 129, 138, 141, 143, 148, 151, 171, 176, 187, 193, 202,
       203, 212, 213, 214, 215, 259, 285, 286, 325, 337, 361, 372, 385,
       397, 399], dtype=int64),)


In [83]:
#print the serial number of all the students who are eligible for scholarship 
ser_no= adm_data[:,0]
print(ser_no)
ser_no[indx]
print(ser_no[indx])

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111. 112.
 113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125. 126.
 127. 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139. 140.
 141. 142. 143. 144. 145. 146. 147. 148. 149. 150. 151. 152. 153. 154.
 155. 156. 157. 158. 159. 160. 161. 162. 163. 164. 165. 166. 167. 168.
 169. 170. 171. 172. 173. 174. 175. 176. 177. 178. 179. 180. 181. 182.
 183. 184. 185. 186. 187. 188. 189. 190. 191. 192. 193. 194. 195. 196.
 197. 

In [84]:
print('the number of students eligible for extra scholarship amount:',ser_no[indx].size)

the number of students eligible for extra scholarship amount: 41
